# Generated by Django 5.2.8 on 2025-12-13 13:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('mtn_mobile_money', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], default='cash_on_delivery', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for mobile money', max_length=20)),
                ('account_number', models.CharField(blank=True, help_text='Account number for bank transfer', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes or instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
