# Generated by Django 5.2.8 on 2025-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(blank=True, help_text='Payment gateway used', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Response from payment gateway', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Payment link for redirect-based payments'),
        ),
    ]
