# Generated by Django 4.2.7 on 2026-01-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0003_payment_system_enhanced'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_created_3147e3_idx',
            old_name='payments_pa_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_11cbdd_idx',
            old_name='payments_pa_method_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_reconci_05066a_idx',
            old_name='payments_pa_reconciled_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_request_031847_idx',
            old_name='payments_pt_request_at_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_payment_f7764a_idx',
            old_name='payments_pt_payment_gateway_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notes for customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Full gateway response', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal payment notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Redirect URL for hosted payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('mtn_mobile_money', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], db_index=True, default='cash_on_delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(db_index=True, help_text='Gateway transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Customer-facing reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='processing_time_ms',
            field=models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='request_data',
            field=models.JSONField(help_text='Sanitized request data sent to gateway'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='response_data',
            field=models.JSONField(blank=True, help_text='Full response from gateway', null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.TextField(help_text='Reason for refund'),
        ),
    ]
