# Generated by Django 6.0.1 on 2026-01-22 17:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_menuitem_average_rating_menuitem_total_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('vital', 'Vital Signs'), ('wellness', 'Wellness Indicators'), ('custom', 'Custom Metric')], max_length=20)),
                ('normal_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('normal_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('alert_threshold_min', models.DecimalField(blank=True, decimal_places=2, help_text='Value below this triggers alert', max_digits=8, null=True)),
                ('alert_threshold_max', models.DecimalField(blank=True, decimal_places=2, help_text='Value above this triggers alert', max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Metric Type',
                'verbose_name_plural': 'Health Metric Types',
                'ordering': ['category', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('recorded_time', models.TimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('conditions', models.CharField(blank=True, help_text="e.g., 'After exercise', 'Before meal', 'Fasting'", max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_metrics/')),
                ('is_alert_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_tracking.healthmetrictype')),
            ],
            options={
                'verbose_name': 'Daily Health Metric',
                'verbose_name_plural': 'Daily Health Metrics',
                'ordering': ['-recorded_date', '-recorded_time'],
                'unique_together': {('user', 'metric_type', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('goal_progress', 'Goal Progress Report'), ('meal_analysis', 'Meal Analysis Report'), ('custom', 'Custom Report')], max_length=20)),
                ('report_title', models.CharField(max_length=255)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('metrics_summary', models.JSONField(blank=True, default=dict)),
                ('goal_progress', models.JSONField(blank=True, default=dict)),
                ('meal_analysis', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('key_findings', models.TextField(blank=True)),
                ('is_shared_with_nutritionist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Report',
                'verbose_name_plural': 'Health Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MealEffectivenessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_overall_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('avg_satisfaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('avg_digestibility', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('avg_energy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('avg_mood', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('effectiveness_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weighted effectiveness (0-100)', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_effectiveness', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Meal Effectiveness Score',
                'verbose_name_plural': 'Meal Effectiveness Scores',
            },
        ),
        migrations.CreateModel(
            name='PatientHealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('energy', 'Increase Energy'), ('fitness', 'Improve Fitness'), ('digestion', 'Better Digestion'), ('sleep', 'Improve Sleep'), ('custom', 'Custom Goal')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_public', models.BooleanField(default=False, help_text='Share with nutritionist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_in_goals', to='health_tracking.healthmetrictype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Health Goal',
                'verbose_name_plural': 'Patient Health Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=200)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_date', models.DateField()),
                ('achievement_order', models.IntegerField(default=1)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='health_tracking.patienthealthgoal')),
            ],
            options={
                'verbose_name': 'Goal Milestone',
                'verbose_name_plural': 'Goal Milestones',
                'ordering': ['achievement_order'],
            },
        ),
        migrations.CreateModel(
            name='MealReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '⭐ Poor'), (2, '⭐⭐ Fair'), (3, '⭐⭐⭐ Good'), (4, '⭐⭐⭐⭐ Very Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('digestibility', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('energy_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('allergies_or_issues', models.CharField(blank=True, max_length=255)),
                ('date_consumed', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('time_consumed', models.TimeField(default=django.utils.timezone.now)),
                ('health_condition_at_time', models.CharField(blank=True, help_text="e.g., 'Tired', 'Stressed', 'Hungry', 'Full'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reviews', to='menu.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Review',
                'verbose_name_plural': 'Meal Reviews',
                'ordering': ['-date_consumed', '-time_consumed'],
                'unique_together': {('user', 'meal', 'date_consumed')},
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('unusual_metric', 'Unusual Metric Reading'), ('goal_achieved', 'Goal Achieved'), ('goal_at_risk', 'Goal At Risk'), ('milestone_reached', 'Milestone Reached'), ('health_trend', 'Health Trend Alert'), ('medication_reminder', 'Medication Reminder'), ('custom', 'Custom Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('notify_nutritionist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='health_tracking.dailyhealthmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='health_tracking.patienthealthgoal')),
            ],
            options={
                'verbose_name': 'Health Alert',
                'verbose_name_plural': 'Health Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user'], name='health_trac_created_e855b7_idx'), models.Index(fields=['severity', 'is_acknowledged'], name='health_trac_severit_035c2b_idx')],
            },
        ),
    ]
