# Generated by Django 6.0.1 on 2026-01-22 17:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('discount_type', models.CharField(max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_audience', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('unique_customers', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vip_orders', models.IntegerField(default=0)),
                ('subscription_orders', models.IntegerField(default=0)),
                ('referral_orders', models.IntegerField(default=0)),
                ('cash_orders', models.IntegerField(default=0)),
                ('mobile_money_orders', models.IntegerField(default=0)),
                ('bank_transfer_orders', models.IntegerField(default=0)),
                ('card_orders', models.IntegerField(default=0)),
                ('vip_discounts_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loyalty_discounts_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('referral_discounts_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Analytics Snapshot',
                'verbose_name_plural': 'Daily Analytics Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_influenced', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customers_reached', models.IntegerField(default=0)),
                ('customers_converted', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of reached customers who converted', max_digits=5)),
                ('roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Return on investment percentage', max_digits=8)),
                ('tracked_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='analytics.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Performance',
                'verbose_name_plural': 'Campaign Performance',
                'ordering': ['-campaign', '-tracked_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('first_order_date', models.DateTimeField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_order', models.IntegerField(default=0)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('churn_risk', models.BooleanField(default=False, help_text='No order in 60+ days')),
                ('vip_tier_current', models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20)),
                ('subscription_active', models.BooleanField(default=False)),
                ('loyalty_points_earned', models.IntegerField(default=0)),
                ('loyalty_points_redeemed', models.IntegerField(default=0)),
                ('loyalty_value_redeemed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('referral_count', models.IntegerField(default=0)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_discounts_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vip_discounts_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Metrics',
                'verbose_name_plural': 'Customer Metrics',
                'ordering': ['-lifetime_value'],
            },
        ),
        migrations.CreateModel(
            name='PageViewAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('view_count', models.IntegerField(default=1)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-view_count'],
                'unique_together': {('page_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RevenueStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('channel', models.CharField(choices=[('direct_order', 'Direct Meal Orders'), ('subscription', 'Subscription Plans'), ('vip_upgrade', 'VIP Tier Upgrade'), ('corporate', 'Corporate Contracts'), ('catering', 'Catering Services'), ('referral', 'Referral Bonuses'), ('loyalty', 'Loyalty Redemptions')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-amount'],
                'indexes': [models.Index(fields=['-date', 'channel'], name='analytics_r_date_679594_idx')],
                'unique_together': {('date', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view_menu', 'View Menu'), ('add_to_cart', 'Add to Cart'), ('start_checkout', 'Start Checkout'), ('complete_order', 'Complete Order'), ('subscribe', 'Subscribe'), ('referral_click', 'Referral Click')], max_length=50)),
                ('session_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Event',
                'verbose_name_plural': 'Conversion Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='analytics_c_timesta_38630f_idx')],
            },
        ),
    ]
