# Generated by Django 6.0 on 2026-01-20 15:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions')),
                ('current_conditions', models.TextField(blank=True, help_text='Ongoing health conditions')),
                ('medications', models.TextField(blank=True, help_text='Current medications')),
                ('allergies', models.TextField(blank=True, help_text='Food allergies (comma-separated)')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Dietary restrictions')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('prescription_date', models.DateField()),
                ('meal_requirements', models.TextField(help_text='Specific meal requirements prescribed by doctor')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Additional dietary restrictions')),
                ('calorie_target', models.IntegerField(blank=True, help_text='Daily calorie target', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_target_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescriptions', to='health_profiles.healthprofile')),
            ],
            options={
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientNutritionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PRE_SERVICE', 'Pre-Service Assessment'), ('POST_SERVICE', 'Post-Service Assessment'), ('FOLLOW_UP', 'Follow-up Assessment')], max_length=20)),
                ('status', models.CharField(choices=[('MALNOURISHED', 'Malnourished'), ('AT_RISK', 'At Risk'), ('NORMAL', 'Normal'), ('OVERWEIGHT', 'Overweight'), ('OBESE', 'Obese')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('muac_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-Upper Arm Circumference', max_digits=5, null=True)),
                ('nutritionist_notes', models.TextField(blank=True)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_assessments', to=settings.AUTH_USER_MODEL)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_statuses', to='health_profiles.healthprofile')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_admission_date', models.DateField()),
                ('hospital_discharge_date', models.DateField(blank=True, null=True)),
                ('admission_reason', models.TextField()),
                ('infection_status', models.BooleanField(default=False, help_text='Infection present during stay')),
                ('infection_type', models.CharField(blank=True, max_length=100)),
                ('current_outcome', models.CharField(choices=[('RECOVERING', 'Recovering'), ('IMPROVED', 'Improved'), ('STABLE', 'Stable'), ('DECLINED', 'Declined'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='RECOVERING', max_length=20)),
                ('recovery_notes', models.TextField(blank=True)),
                ('attending_physician', models.CharField(blank=True, max_length=100)),
                ('nutrition_intervention_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_metrics', to='health_profiles.healthprofile')),
            ],
            options={
                'ordering': ['-hospital_admission_date'],
            },
        ),
    ]
