# Generated by Django 6.0.1 on 2026-02-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available - Can accept assignments'), ('busy', 'Busy - Currently in consultation'), ('break', 'On Break'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('max_concurrent_checks', models.IntegerField(default=3)),
                ('current_assignments', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('preferred_check_types', models.CharField(blank=True, help_text='Comma-separated list', max_length=200)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_completed_checks', models.IntegerField(default=0)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('next_available_at', models.DateTimeField(blank=True, null=True)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_type', models.CharField(choices=[('initial', 'Initial Health Assessment'), ('follow_up', 'Follow-up Consultation'), ('nutrition', 'Nutrition Assessment'), ('medical', 'Medical Check'), ('wellness', 'Wellness Check')], default='wellness', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting Assignment'), ('assigned', 'Assigned - Consultant Assigned'), ('in_progress', 'In Progress - Consultation Ongoing'), ('completed', 'Completed - Consultation Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent - Immediate attention needed'), ('high', 'High - Within 24 hours'), ('normal', 'Normal - Within 3 days'), ('low', 'Low - Flexible scheduling')], default='normal', max_length=20)),
                ('description', models.TextField(help_text="Patient's health concerns or reason for check")),
                ('medical_history', models.TextField(blank=True, help_text='Relevant medical history')),
                ('current_symptoms', models.TextField(blank=True, help_text='Current symptoms if any')),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_time_slot', models.CharField(blank=True, help_text="e.g., '09:00-10:00'", max_length=50)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('auto_assigned', models.BooleanField(default=False, help_text='Auto-assigned by system')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_reason', models.CharField(blank=True, max_length=200)),
                ('consultant_notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_health_checks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Successfully Assigned'), ('no_available', 'No Available Consultant'), ('error', 'Assignment Error')], max_length=20)),
                ('message', models.TextField()),
                ('assigned_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='health_profiles.healthcheck')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['patient', 'status'], name='health_prof_patient_9509f1_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['status', 'assigned_consultant'], name='health_prof_status_813665_idx'),
        ),
    ]
