# Generated by Django 6.0.1 on 2026-02-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_menuitem_average_rating_menuitem_total_reviews'),
        ('orders', '0004_order_account_number_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Patient Education Categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(help_text='Ward location/building', max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of beds in ward')),
                ('description', models.TextField(blank=True, help_text='Ward description and specialties')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealNutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(help_text='Calories per serving')),
                ('protein_g', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=5)),
                ('carbohydrates_g', models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams', max_digits=5)),
                ('fat_g', models.DecimalField(decimal_places=2, help_text='Fat in grams', max_digits=5)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, help_text='Dietary fiber in grams', max_digits=5)),
                ('sodium_mg', models.PositiveIntegerField(default=0, help_text='Sodium in milligrams')),
                ('potassium_mg', models.PositiveIntegerField(default=0, help_text='Potassium in milligrams')),
                ('calcium_mg', models.PositiveIntegerField(default=0, help_text='Calcium in milligrams')),
                ('iron_mg', models.DecimalField(decimal_places=2, default=0, help_text='Iron in milligrams', max_digits=5)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('contains_dairy', models.BooleanField(default=False)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('contains_shellfish', models.BooleanField(default=False)),
                ('contains_eggs', models.BooleanField(default=False)),
                ('contains_soy', models.BooleanField(default=False)),
                ('allergen_warnings', models.TextField(blank=True, help_text='Additional allergen warnings (comma-separated)')),
                ('key_ingredients', models.TextField(blank=True, help_text='Key ingredients (comma-separated)')),
                ('suitable_for_diets', models.CharField(blank=True, help_text='Suitable diet types: diabetic, low-sodium, high-protein, vegetarian, vegan, etc.', max_length=255)),
                ('preparation_notes', models.TextField(blank=True)),
                ('serving_size', models.CharField(default='1 plate', help_text='Standard serving size', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_info', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Meal Nutrition Info',
                'verbose_name_plural': 'Meal Nutrition Info',
            },
        ),
        migrations.CreateModel(
            name='PatientEducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Main educational content')),
                ('content_type', models.CharField(choices=[('diet_info', 'Diet Information'), ('recovery_guide', 'Recovery Guide'), ('health_tip', 'Health Tip'), ('medication_info', 'Medication Information'), ('exercise_guide', 'Exercise Guide'), ('video_guide', 'Video Guide'), ('infographic', 'Infographic')], max_length=50)),
                ('target_role', models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('both', 'Both Patient & Caregiver')], default='both', max_length=20)),
                ('applicable_diet_types', models.CharField(choices=[('diabetic', 'Diabetic Diet'), ('low_sodium', 'Low Sodium Diet'), ('high_protein', 'High Protein Diet'), ('low_fat', 'Low Fat Diet'), ('renal', 'Renal Diet'), ('cardiac', 'Cardiac Diet'), ('ulcer', 'Ulcer Diet'), ('general', 'General Diet'), ('all', 'All Diet Types')], default='general', help_text='Which diet types this content applies to', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Educational image or infographic', null=True, upload_to='education/')),
                ('video_url', models.URLField(blank=True, help_text='Link to educational video')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF document', null=True, upload_to='education/pdfs/')),
                ('is_published', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_contents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='hospital_wards.patienteducationcategory')),
            ],
            options={
                'verbose_name': 'Patient Education Content',
                'verbose_name_plural': 'Patient Education Contents',
                'ordering': ['category', 'ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_beds', models.PositiveIntegerField(default=0)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('maintenance_beds', models.PositiveIntegerField(default=0)),
                ('reserved_beds', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='hospital_wards.ward')),
            ],
            options={
                'verbose_name_plural': 'Ward Availabilities',
            },
        ),
        migrations.CreateModel(
            name='CaregiverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('meal_scheduled', 'Meal Scheduled'), ('nutrition_info', 'Nutrition Information'), ('education_assigned', 'Education Material Assigned'), ('appointment_reminder', 'Appointment Reminder'), ('custom_message', 'Custom Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_notifications', to='orders.order')),
                ('related_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_notifications', to='hospital_wards.patienteducationcontent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['caregiver', '-created_at'], name='hospital_wa_caregiv_d1d324_idx'), models.Index(fields=['is_read', '-created_at'], name='hospital_wa_is_read_552f28_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientEducationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_progress', to='hospital_wards.patienteducationcontent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Education Progress',
                'verbose_name_plural': 'Patient Education Progress',
                'unique_together': {('patient', 'content')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(help_text='Time slot starts at')),
                ('end_time', models.TimeField(help_text='Time slot ends at')),
                ('max_bookings', models.PositiveIntegerField(default=50)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='hospital_wards.ward')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('ward', 'date', 'meal_type', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='WardBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_bed', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital_wards.ward')),
            ],
            options={
                'ordering': ['ward', 'bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
        migrations.CreateModel(
            name='WardDeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('supplement', 'Supplement')], max_length=20)),
                ('scheduled_time', models.TimeField(help_text='Typical delivery time for this meal')),
                ('average_delivery_minutes', models.PositiveIntegerField(default=30, help_text='Average minutes to deliver all meals in ward')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_routes', to='hospital_wards.ward')),
            ],
            options={
                'ordering': ['ward', 'scheduled_time'],
                'unique_together': {('ward', 'meal_type')},
            },
        ),
    ]
