# Generated by Django 6.0.1 on 2026-02-01 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_wards', '0002_bedmaintenanceschedule_patientadmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notification_type', models.CharField(choices=[('admission', 'Admission Notification'), ('discharge', 'Discharge Notification'), ('transfer', 'Transfer Notification'), ('appointment', 'Appointment Reminder'), ('medication', 'Medication Reminder'), ('follow_up', 'Follow-up Reminder'), ('alert', 'Medical Alert')], max_length=50)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField(help_text='Use {patient_name}, {bed_number}, {ward_name} as variables')),
                ('sms_body', models.CharField(help_text='Keep under 160 characters for SMS. Use {patient_name}, {bed_number} as variables', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('import_patients', 'Import Patients'), ('export_patients', 'Export Patients'), ('bulk_discharge', 'Bulk Discharge'), ('bulk_assignment', 'Bulk Assignment'), ('export_report', 'Export Report')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='bulk_operations/input/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='bulk_operations/output/')),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('successful_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='hospital_wa_status_7d9512_idx'), models.Index(fields=['initiated_by', '-created_at'], name='hospital_wa_initiat_ca4eb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('admission', 'Admission Notification'), ('discharge', 'Discharge Notification'), ('transfer', 'Transfer Notification'), ('appointment', 'Appointment Reminder'), ('medication', 'Medication Reminder'), ('follow_up', 'Follow-up Reminder'), ('alert', 'Medical Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_in_app', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Send at specific time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hospital_wards.patientadmission')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='hospital_wa_recipie_4458c4_idx'), models.Index(fields=['notification_type', '-created_at'], name='hospital_wa_notific_4eef64_idx')],
            },
        ),
    ]
