# Generated by Django 6.0.1 on 2026-02-02 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_wards', '0003_notificationtemplate_bulkoperation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('admission_notifications', models.BooleanField(default=True)),
                ('discharge_notifications', models.BooleanField(default=True)),
                ('transfer_notifications', models.BooleanField(default=True)),
                ('alert_notifications', models.BooleanField(default=True)),
                ('appointment_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time (HH:MM)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time (HH:MM)', null=True)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest')], default='instant', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
