# Generated by Django 4.2.7 on 2026-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatecontract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Corporate Contract', 'verbose_name_plural': 'Corporate Contracts'},
        ),
        migrations.AddField(
            model_name='corporatecontract',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporatecontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending_renewal', 'Pending Renewal')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='CorporateEmployee',
        ),
    ]
