# Generated by Django 5.2.8 on 2025-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_light',
            field=models.BooleanField(default=False, help_text='Whether customer has light. Only customers without light can register.'),
        ),
    ]
