# Generated by Django 4.2.7 on 2026-01-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_has_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medical_alerts',
            field=models.TextField(blank=True, help_text='Critical medical alerts or allergies'),
        ),
    ]
