# Generated by Django 6.0.1 on 2026-01-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rbac_extended_profile'),
        ('accounts', '0003_profile_medical_alerts'),
    ]

    operations = [
    ]
