# Generated by Django 6.0.1 on 2026-02-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260201_0136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_role_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_user_role_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='assigned_patient',
            field=models.ForeignKey(blank=True, help_text='Patient this caregiver is assigned to', limit_choices_to={'profile__role': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_zones',
            field=models.CharField(blank=True, help_text='Comma-separated list of delivery zones', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, help_text='Department assignment (e.g., Kitchen, Delivery, Support)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID for staff members', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether user account is active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_available_for_delivery',
            field=models.BooleanField(default=True, help_text='Whether delivery person is available for orders'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license number (for nutritionists and medical staff)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Direct manager for this staff member', limit_choices_to={'role__in': ['hospital_manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patient_relationship',
            field=models.CharField(blank=True, help_text='Relationship to patient (parent, spouse, sibling, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('nutritionist', 'Nutritionist'), ('medical_staff', 'Medical Staff'), ('chef', 'Chef'), ('kitchen_staff', 'Kitchen Staff'), ('delivery_person', 'Delivery Person'), ('support_staff', 'Support Staff'), ('hospital_manager', 'Hospital Manager'), ('admin', 'System Administrator')], default='patient', help_text='User role determining dashboard and permissions', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sms_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via SMS'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Professional specialization', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], default='active', help_text='Account status', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vehicle_registration',
            field=models.CharField(blank=True, help_text='Vehicle registration number for delivery personnel', max_length=50),
        ),
    ]
