# Generated by Django 6.0.1 on 2026-02-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_adminlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminlog',
            new_name='admin_dashb_timesta_782497_idx',
            old_name='admin_dash_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='adminlog',
            new_name='admin_dashb_admin_u_893dde_idx',
            old_name='admin_dash_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='adminlog',
            new_name='admin_dashb_action_576da5_idx',
            old_name='admin_dash_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='adminlog',
            new_name='admin_dashb_model_n_7134c5_idx',
            old_name='admin_dash_model_timestamp_idx',
        ),
    ]
