"""
Django settings for dusangire project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: read secret key from environment in production
# Keep the hard-coded key as a fallback only for local development.
SECRET_KEY = config('SECRET_KEY', default='!@5x2i!jzcrbso%1)d0_xhnk2cmtr!w0+l$hwcmo$1j0nmj!7v')

# DEBUG should be switched off in production via environment variable
# Example: export DEBUG=False
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS must be configured in production. Include PythonAnywhere domain.
ALLOWED_HOSTS = [h for h in config('ALLOWED_HOSTS', default='dusa2026.pythonanywhere.com,localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for ASGI
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'channels',  # Django Channels for WebSocket support
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    
    # Local apps
    'accounts',
    'menu',
    'orders',
    'delivery',
    'payments',
    'admin_dashboard',
    'subscriptions',
    'loyalty',
    'corporate',
    'catering',
    'notifications',
    'reviews',
    'support',
    'patients',
    'nutritionist_dashboard',
    'customer_dashboard',
    'health_profiles',
    'analytics',
    'health_tracking',
    'hospital_wards',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = not DEBUG  # Enforce HTTPS in production
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = True

ROOT_URLCONF = 'dusangire.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'dusangire.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'menu:menu_list'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Email Configuration for Password Reset & Notifications
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Console backend for development
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # or your email provider
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'  # Use environment variables in production
EMAIL_FROM_USER = 'rukundojeandedieu670@gmail.com'  # Default from email address
DEFAULT_FROM_EMAIL = 'rukundojeandedieu670@gmail.com'
CONTACT_EMAIL = 'rukundojeandedieu670@gmail.com'
CONTACT_PHONE = '+250792392072'
SUPPORT_EMAIL = 'rukundojeandedieu670@gmail.com'
SUPPORT_PHONE = '+250792392072'
PASSWORD_RESET_TIMEOUT = 3600  # Password reset link valid for 1 hour (in seconds)

# Site Configuration
SITE_ID = 1
SITE_NAME = 'Dusangire Health Platform'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Payment Gateway Configuration
# Hospital-ready payment integration settings

# Payment Environment: 'sandbox' or 'production'
PAYMENT_ENVIRONMENT = 'sandbox'  # Change to 'production' when ready

# Site URL for payment callbacks
SITE_URL = 'http://localhost:8000'  # Update with your actual domain

# Currency and Country Settings
CURRENCY_CODE = 'UGX'  # Uganda Shilling
COUNTRY_CODE = 'UG'  # Uganda

# MTN Mobile Money API Configuration
MTN_MOMO_API_KEY = ''  # Set in environment variables
MTN_MOMO_API_SECRET = ''  # Set in environment variables
MTN_MOMO_SUBSCRIPTION_KEY = ''  # Set in environment variables

# Airtel Money API Configuration
AIRTEL_MONEY_CLIENT_ID = ''  # Set in environment variables
AIRTEL_MONEY_CLIENT_SECRET = ''  # Set in environment variables

# Flutterwave API Configuration (for Bank Transfer and Card Payments)
FLUTTERWAVE_PUBLIC_KEY = ''  # Set in environment variables
FLUTTERWAVE_SECRET_KEY = ''  # Set in environment variables
FLUTTERWAVE_SECRET_HASH = ''  # Set in environment variables (for webhook verification)

# Site ID for allauth
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    # Django backend
    'django.contrib.auth.backends.ModelBackend',
    
    # Allauth specific authentication methods
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Settings
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_FIELDS = [
    'email*',
    'password1*',
    'password2*',
]
SOCIALACCOUNT_AUTO_SIGNUP = True

# Google OAuth Configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': config('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': config('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
            'key': ''
        }
    }
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Redirect URLs after OAuth
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'
HOSPITAL_ACQUISITION_MODE = True  # Enable hospital-specific features
# Django Channels Configuration
ASGI_APPLICATION = 'dusangire.asgi.application'

# Channel Layers Configuration (Redis backend for production)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],  # Local Redis or use remote for production
            'capacity': 1500,
            'expiry': 10,
        }
    }
}

# In-memory channel layer for development (if Redis is not available)
# Uncomment for local development without Redis
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }