# Generated by Django 5.2.8 on 2025-12-14 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_average_rating_menuitem_total_reviews'),
        ('orders', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', '-is_verified_purchase']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'menu_item')},
        ),
        migrations.AddField(
            model_name='review',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Whether this review has been flagged for moderation'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Admin notes for moderation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Your review comment (minimum 10 characters)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, help_text='Optional review title', max_length=200),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['menu_item', 'is_approved', '-created_at'], name='reviews_rev_menu_it_a17393_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase', '-created_at'], name='reviews_rev_is_veri_727b5e_idx'),
        ),
    ]
