# Generated by Django 6.0 on 2026-01-16 14:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientassignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Assignment', 'verbose_name_plural': 'Client Assignments'},
        ),
        migrations.AlterModelOptions(
            name='nutritionistprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nutritionist Profile', 'verbose_name_plural': 'Nutritionist Profiles'},
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Assignment end date (null if active)', null=True),
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about assignment', null=True),
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', help_text='Assignment status', max_length=20),
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license number', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='max_clients',
            field=models.IntegerField(default=50, help_text='Maximum number of clients allowed'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', help_text='Current status', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='client',
            field=models.ForeignKey(help_text='Assigned client', on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='nutritionist',
            field=models.ForeignKey(help_text='Assigned nutritionist', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Assignment start date'),
        ),
        migrations.AlterField(
            model_name='nutritionistprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionistprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Area of specialization', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionistprofile',
            name='user',
            field=models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='nutritionistprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clientassignment',
            unique_together={('nutritionist', 'client')},
        ),
        migrations.AddIndex(
            model_name='clientassignment',
            index=models.Index(fields=['nutritionist', 'status'], name='nutritionis_nutriti_89c9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='clientassignment',
            index=models.Index(fields=['client'], name='nutritionis_client__8bd535_idx'),
        ),
        migrations.AddIndex(
            model_name='clientassignment',
            index=models.Index(fields=['status'], name='nutritionis_status_b4bd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientassignment',
            index=models.Index(fields=['-created_at'], name='nutritionis_created_769b51_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionistprofile',
            index=models.Index(fields=['user'], name='nutritionis_user_id_93cc56_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionistprofile',
            index=models.Index(fields=['status'], name='nutritionis_status_d09fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionistprofile',
            index=models.Index(fields=['-created_at'], name='nutritionis_created_2ba25e_idx'),
        ),
    ]
