# Generated by Django 5.2.10 on 2026-01-29 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist_dashboard', '0004_nutritionistavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientassignment',
            unique_together={('nutritionist', 'client')},
        ),
    ]
