# Generated by Django 5.2.8 on 2025-12-13 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_menuitem_image'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per billing cycle', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('meals_per_cycle', models.PositiveIntegerField(default=1, help_text='Number of meals per billing cycle')),
                ('duration_days', models.PositiveIntegerField(help_text='Duration of plan in days (e.g., 30 for monthly)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_items', models.ManyToManyField(blank=True, help_text='Specific menu items included (leave empty for all items)', related_name='subscription_plans', to='menu.menuitem')),
            ],
            options={
                'ordering': ['plan_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('paused_until', models.DateField(blank=True, help_text='Resume date if paused', null=True)),
                ('preferred_delivery_time', models.TimeField(blank=True, help_text='Preferred delivery time', null=True)),
                ('dietary_preferences', models.TextField(blank=True, help_text='Dietary preferences for meal selection')),
                ('auto_order_enabled', models.BooleanField(default=True, help_text='Automatically create orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Date this order was scheduled for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_order', to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
