# Generated by Django 5.2.8 on 2025-12-13 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (e.g., 10.00 for 10% off)', max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscribers_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of active subscribers'),
        ),
    ]
