# Generated by Django 5.2.8 on 2025-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_average_rating_menuitem_total_reviews'),
        ('subscriptions', '0002_subscriptionplan_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renewal_enabled',
            field=models.BooleanField(default=False, help_text='Automatically renew subscription when it expires'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='delivery_address_id',
            field=models.IntegerField(blank=True, help_text='Cached delivery address ID', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='preferred_meals',
            field=models.ManyToManyField(blank=True, help_text="User's preferred meals for this subscription", related_name='preferred_subscriptions', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='dietary_preferences',
            field=models.TextField(blank=True, help_text='Dietary preferences for meal selection (e.g., vegetarian, diabetic-friendly)'),
        ),
    ]
