# Generated by Django 4.2.7 on 2026-01-16 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_rename_payments_pa_created_idx_payments_pa_created_3147e3_idx_and_more'),
        ('subscriptions', '0003_usersubscription_auto_renewal_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('spending_ytd', models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date spending in RWF', max_digits=12)),
                ('spending_total', models.DecimalField(decimal_places=2, default=0, help_text='Total lifetime spending', max_digits=15)),
                ('promotion_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Extra loyalty points percentage (e.g., 5 for +5%)', max_digits=5)),
                ('access_level', models.PositiveIntegerField(default=1, help_text='1=Bronze, 2=Silver, 3=Gold, 4=Platinum')),
                ('achieved_at', models.DateField(help_text='When tier was achieved')),
                ('next_tier_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Spending needed for next tier', max_digits=12)),
                ('benefits_list', models.JSONField(blank=True, default=dict, help_text='Tier benefits (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_tier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'VIP Tiers',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAutoRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_renew_enabled', models.BooleanField(default=False)),
                ('payment_method_id', models.CharField(blank=True, help_text='Saved payment method ID', max_length=50)),
                ('renewal_date', models.DateField(help_text='Next scheduled renewal date')),
                ('renewal_interval_days', models.PositiveIntegerField(default=30, help_text='Days between renewals')),
                ('notification_sent', models.DateTimeField(blank=True, help_text='When reminder notification was sent', null=True)),
                ('notification_days_before', models.PositiveIntegerField(default=3, help_text='Days before renewal to send notification')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of failed renewal attempts')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When to retry if failed', null=True)),
                ('last_renewal_status', models.CharField(blank=True, help_text='Status of last renewal attempt', max_length=50)),
                ('last_renewal_at', models.DateTimeField(blank=True, help_text='When last renewal was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_renewal', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name_plural': 'Subscription Auto-Renewals',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='Current loyalty points balance')),
                ('earned_total', models.PositiveIntegerField(default=0, help_text='Total points earned (lifetime)')),
                ('redeemed_total', models.PositiveIntegerField(default=0, help_text='Total points redeemed (lifetime)')),
                ('subscription_bonus_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for earning points (1.0 = 1pt per 100RWF, 1.05 = 5% bonus)', max_digits=5)),
                ('expires_at', models.DateField(blank=True, help_text='Points expiration date (null = no expiration)', null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Points',
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, help_text='Unique referral code', max_length=20, unique=True)),
                ('referral_link', models.URLField(blank=True)),
                ('referrer_bonus_rwf', models.PositiveIntegerField(default=10000, help_text='Bonus for referrer in RWF')),
                ('referrer_bonus_points', models.PositiveIntegerField(default=100, help_text='Bonus points for referrer')),
                ('referee_discount_percent', models.DecimalField(decimal_places=2, default=10, help_text='Discount for referee on first purchase (%)', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When referral link expires')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='subscriptio_referre_d90fc0_idx'), models.Index(fields=['referral_code'], name='subscriptio_referra_b3d107_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Points Earned'), ('REDEEM', 'Points Redeemed'), ('BONUS', 'Bonus Points'), ('ADJUSTMENT', 'Admin Adjustment')], max_length=20)),
                ('points_amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('related_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_fa6ec6_idx'), models.Index(fields=['transaction_type', '-created_at'], name='subscriptio_transac_b7f7fd_idx')],
            },
        ),
    ]
