# Generated by Django 6.0 on 2026-01-20 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_average_rating_menuitem_total_reviews'),
        ('payments', '0004_rename_payments_pa_created_idx_payments_pa_created_3147e3_idx_and_more'),
        ('subscriptions', '0004_viptier_subscriptionautorenewal_loyaltypoints_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscription',
            new_name='Subscription',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', '-created_at'], name='subscriptio_user_id_0a99db_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='subscriptio_status_5ff966_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['auto_order_enabled', 'status'], name='subscriptio_auto_or_1a31ee_idx'),
        ),
    ]
