# Generated by Django 6.0 on 2026-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_usersubscription_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('detox', 'Detox'), ('keto', 'Keto'), ('diabetic', 'Diabetic-Friendly'), ('vegan', 'Vegan'), ('athlete', 'Athlete/Performance')], default='general', max_length=20),
        ),
    ]
