# Generated by Django 5.2.8 on 2025-12-12 18:09

import menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this menu item. Recommended size: 800x600px. Max size: 5MB. Formats: JPEG, PNG, WEBP', null=True, upload_to='menu_items/', validators=[menu.validators.validate_image_size, menu.validators.validate_image_format, menu.validators.validate_image_dimensions]),
        ),
    ]
