# Generated by Django 5.2.8 on 2025-12-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews (1.00 to 5.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of approved reviews'),
        ),
    ]
