# Generated by Django 6.0 on 2026-01-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='healthprofile',
            new_name='patients_he_user_id_29226f_idx',
            old_name='patients_hea_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='healthprofile',
            new_name='patients_he_admissi_c641d2_idx',
            old_name='patients_hea_admissi_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmealhistory',
            new_name='patients_pa_patient_eb564f_idx',
            old_name='patients_pat_patient_meal_idx',
        ),
        migrations.RenameIndex(
            model_name='patientnutritionstatus',
            new_name='patients_pa_patient_1a8ea2_idx',
            old_name='patients_pat_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverymetrics',
            new_name='patients_re_patient_f56d4b_idx',
            old_name='patients_rec_patient_idx',
        ),
    ]
