# Generated by Django 6.0.1 on 2026-02-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0004_order_account_number_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Special requests or customizations (e.g., no salt, extra spice, allergies)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryaddress'),
        ),
    ]
